import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:usando_api/api.dart';

void main() {
  runApp(MaterialApp(
    home: Home(),
  ));
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  List<Autogenerated> _api;

  Future<List<Autogenerated>> _getUser() async {
    try {
      List<Autogenerated> listUser = List();
      final response =
          await http.get("https://jsonplaceholder.typicode.com/users");
      if (response.statusCode == 200) {
        var decodeJSON = jsonDecode(response.body);
        decodeJSON
            .forEach((item) => listUser.add(Autogenerated.fromJson(item)));
        return listUser;
      } else {
        print("Erro ao carregar lista");
        return null;
      }
    } catch (e) {
      print("Erro ao carregar lista");
      return null;
    }
  }

  @override
  void initState() {
    super.initState();
    _getUser().then((map) async {
      setState(() {
        _api = map;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("requisitanto API"),
        centerTitle: true,
        backgroundColor: Colors.black,
      ),
      body: Container(
        child: ListView.builder(
          
          itemBuilder: (context, index) {
            return Container(
              padding: EdgeInsets.all(10),
              child: Container(
                color: Colors.black,
                height: 80,
                child: Column(
                  children: <Widget>[
                    Text(('$index'), style: TextStyle(color: Colors.white)),
                    Text(
                      _api[index].name,
                      style: TextStyle(color: Colors.white),
                    ),
                    Text(_api[index].email,
                        style: TextStyle(color: Colors.white)),
                    Text(_api[index].phone,
                        style: TextStyle(color: Colors.white)),
                  ],
                ),
              ),
            );
          },
          itemCount: 10,
        ),
      ),
    );
  }
}
